# Generated by Django 5.2.3 on 2025-07-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section_type',
            field=models.CharField(choices=[('hero', 'Hero'), ('features', 'Features'), ('custom', 'Custom')], max_length=50),
        ),
    ]
