# Generated by Django 4.2.19 on 2025-07-14 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_menu_slug_alter_menu_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='button_text',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='section',
            name='custom_css',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='grapesjs_html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='section_images/'),
        ),
        migrations.AlterField(
            model_name='section',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
