# Generated by Django 4.2.19 on 2025-07-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_section_button_text_section_custom_css_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='button_text',
        ),
        migrations.RemoveField(
            model_name='section',
            name='content',
        ),
        migrations.RemoveField(
            model_name='section',
            name='custom_css',
        ),
        migrations.RemoveField(
            model_name='section',
            name='grapesjs_html',
        ),
        migrations.AddField(
            model_name='section',
            name='bottom_link',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='bottom_text',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='full_width',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='section',
            name='sub_title',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='section_images/'),
        ),
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
