# Generated by Django 4.2.19 on 2025-07-14 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_section_button_text_remove_section_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('sub_title', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='card_images/')),
                ('button_text', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('button_link', models.URLField(blank=True, default='', null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='api.section')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
