# Generated by Django 4.2.19 on 2025-07-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_sectioncard'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='css_class',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='html_id',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sectioncard',
            name='css_class',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sectioncard',
            name='html_id',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
