# Generated by Django 4.2.19 on 2025-07-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_section_css_class_section_html_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='bottom_link',
        ),
        migrations.AddField(
            model_name='section',
            name='button_link',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sectioncard',
            name='button_link',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
