# Generated by Django 4.2.19 on 2025-06-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custompage',
            name='sections',
            field=models.ManyToManyField(blank=True, related_name='pages', to='builder.websection'),
        ),
        migrations.AlterField(
            model_name='custompage',
            name='slug',
            field=models.SlugField(default='', help_text='Used in URL, e.g., /pages/about/', unique=True),
        ),
        migrations.AlterField(
            model_name='custompage',
            name='title',
            field=models.CharField(default='Untitled Page', help_text='Title of the custom page (e.g., Home, About Us)', max_length=255),
        ),
        migrations.AlterField(
            model_name='websection',
            name='html_content',
            field=models.TextField(default='<div>No content available</div>', help_text='Cloned HTML content of the section'),
        ),
        migrations.AlterField(
            model_name='websection',
            name='name',
            field=models.CharField(default='Untitled Section', help_text='Name to identify this section (e.g., Hero Banner)', max_length=255),
        ),
        migrations.AlterField(
            model_name='websection',
            name='selector',
            field=models.CharField(default='body', help_text='CSS selector used to extract this section', max_length=255),
        ),
        migrations.AlterField(
            model_name='websection',
            name='source_url',
            field=models.URLField(default='https://example.com', help_text='Original URL where this section was extracted from'),
        ),
    ]
