# Generated by Django 4.2.19 on 2025-06-21 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0002_alter_custompage_sections_alter_custompage_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.custompage')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.websection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
