# Generated by Django 4.2.19 on 2025-06-23 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0003_pagesection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custompage',
            name='sections',
        ),
        migrations.AddField(
            model_name='websection',
            name='section_type',
            field=models.CharField(choices=[('header', 'Header'), ('footer', 'Footer'), ('hero', 'Hero Section'), ('features', 'Features'), ('pricing', 'Pricing'), ('testimonial', 'Testimonial'), ('cta', 'Call to Action'), ('content', 'Content Block'), ('custom', 'Custom')], default='custom', help_text='Type of this section (e.g., header, footer)', max_length=20),
        ),
    ]
