# Generated by Django 4.2.19 on 2025-07-01 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0004_remove_custompage_sections_websection_section_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditableCSS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='global', max_length=100)),
                ('file_path', models.CharField(default='static/css/global.css', max_length=255)),
            ],
        ),
    ]
