# Generated by Django 4.2.19 on 2025-07-01 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0005_editablecss'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditableJS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='global', max_length=100)),
                ('file_path', models.CharField(default='static/js/global.js', max_length=255)),
            ],
        ),
    ]
