# Generated by Django 4.2.19 on 2025-07-01 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0006_editablejs'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditableJSHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edited_at', models.DateTimeField(auto_now_add=True)),
                ('previous_content', models.TextField()),
                ('new_content', models.TextField()),
                ('editable_js', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.editablejs')),
            ],
        ),
    ]
