# Generated by Django 4.2.19 on 2025-07-02 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0007_editablejshistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='editablecss',
            name='version',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
